[2024-12-26T04:39:04.524+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T04:39:04.551+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_forex_data_dag.transform_and_load_forex_data manual__2024-12-26T04:39:01.726240+00:00 [queued]>
[2024-12-26T04:39:04.566+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_forex_data_dag.transform_and_load_forex_data manual__2024-12-26T04:39:01.726240+00:00 [queued]>
[2024-12-26T04:39:04.567+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T04:39:04.595+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_and_load_forex_data> on 2024-12-26 04:39:01.726240+00:00
[2024-12-26T04:39:04.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=401) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-26T04:39:04.608+0000] {standard_task_runner.py:72} INFO - Started process 403 to run task
[2024-12-26T04:39:04.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transform_forex_data_dag', 'transform_and_load_forex_data', 'manual__2024-12-26T04:39:01.726240+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/flatten.py', '--cfg-path', '/tmp/tmp1w17g4_7']
[2024-12-26T04:39:04.610+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask transform_and_load_forex_data
[2024-12-26T04:39:04.688+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_forex_data_dag.transform_and_load_forex_data manual__2024-12-26T04:39:01.726240+00:00 [running]> on host 4fe538676cbc
[2024-12-26T04:39:04.835+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_forex_data_dag' AIRFLOW_CTX_TASK_ID='transform_and_load_forex_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T04:39:01.726240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T04:39:01.726240+00:00'
[2024-12-26T04:39:04.837+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T04:39:04.857+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-26T04:39:04.859+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-26T04:39:04.860+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-26T04:39:06.168+0000] {cursor.py:1166} INFO - Number of results in first chunk: 0
[2024-12-26T04:39:12.233+0000] {logging_mixin.py:190} INFO - Inserted batch 1
[2024-12-26T04:39:14.500+0000] {logging_mixin.py:190} INFO - Inserted batch 2
[2024-12-26T04:39:16.810+0000] {logging_mixin.py:190} INFO - Inserted batch 3
[2024-12-26T04:39:19.198+0000] {logging_mixin.py:190} INFO - Inserted batch 4
[2024-12-26T04:39:21.286+0000] {logging_mixin.py:190} INFO - Inserted batch 5
[2024-12-26T04:39:23.532+0000] {logging_mixin.py:190} INFO - Inserted batch 6
[2024-12-26T04:39:27.157+0000] {logging_mixin.py:190} INFO - Inserted batch 7
[2024-12-26T04:39:30.174+0000] {logging_mixin.py:190} INFO - Inserted batch 8
[2024-12-26T04:39:33.831+0000] {logging_mixin.py:190} INFO - Inserted batch 9
[2024-12-26T04:39:36.233+0000] {logging_mixin.py:190} INFO - Inserted batch 10
[2024-12-26T04:39:39.537+0000] {logging_mixin.py:190} INFO - Inserted batch 11
[2024-12-26T04:39:41.420+0000] {logging_mixin.py:190} INFO - Inserted batch 12
[2024-12-26T04:39:45.565+0000] {logging_mixin.py:190} INFO - Inserted batch 13
[2024-12-26T04:39:48.286+0000] {logging_mixin.py:190} INFO - Inserted batch 14
[2024-12-26T04:39:50.660+0000] {logging_mixin.py:190} INFO - Inserted batch 15
[2024-12-26T04:39:53.970+0000] {logging_mixin.py:190} INFO - Inserted batch 16
[2024-12-26T04:39:56.282+0000] {logging_mixin.py:190} INFO - Inserted batch 17
[2024-12-26T04:39:58.458+0000] {logging_mixin.py:190} INFO - Inserted batch 18
[2024-12-26T04:40:01.969+0000] {logging_mixin.py:190} INFO - Inserted batch 19
[2024-12-26T04:40:05.214+0000] {logging_mixin.py:190} INFO - Inserted batch 20
[2024-12-26T04:40:07.494+0000] {logging_mixin.py:190} INFO - Inserted batch 21
[2024-12-26T04:40:09.744+0000] {logging_mixin.py:190} INFO - Inserted batch 22
[2024-12-26T04:40:12.119+0000] {logging_mixin.py:190} INFO - Inserted batch 23
[2024-12-26T04:40:14.492+0000] {logging_mixin.py:190} INFO - Inserted batch 24
[2024-12-26T04:40:17.131+0000] {logging_mixin.py:190} INFO - Inserted batch 25
[2024-12-26T04:40:19.918+0000] {logging_mixin.py:190} INFO - Inserted batch 26
[2024-12-26T04:40:21.989+0000] {logging_mixin.py:190} INFO - Inserted batch 27
[2024-12-26T04:40:25.499+0000] {logging_mixin.py:190} INFO - Inserted batch 28
[2024-12-26T04:40:28.142+0000] {logging_mixin.py:190} INFO - Inserted batch 29
[2024-12-26T04:40:31.889+0000] {logging_mixin.py:190} INFO - Inserted batch 30
[2024-12-26T04:40:34.866+0000] {logging_mixin.py:190} INFO - Inserted batch 31
[2024-12-26T04:40:37.692+0000] {logging_mixin.py:190} INFO - Inserted batch 32
[2024-12-26T04:40:41.453+0000] {logging_mixin.py:190} INFO - Inserted batch 33
[2024-12-26T04:40:44.100+0000] {logging_mixin.py:190} INFO - Inserted batch 34
[2024-12-26T04:40:46.291+0000] {logging_mixin.py:190} INFO - Inserted batch 35
[2024-12-26T04:40:48.559+0000] {logging_mixin.py:190} INFO - Inserted batch 36
[2024-12-26T04:40:52.386+0000] {logging_mixin.py:190} INFO - Inserted batch 37
[2024-12-26T04:40:55.024+0000] {logging_mixin.py:190} INFO - Inserted batch 38
[2024-12-26T04:40:56.079+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-26T04:40:56.083+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T04:40:56.085+0000] {process_utils.py:132} INFO - Sending 15 to group 403. PIDs of all processes in the group: [403]
[2024-12-26T04:40:56.086+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 403
[2024-12-26T04:40:56.087+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-26T04:40:56.089+0000] {connection.py:789} INFO - closed
[2024-12-26T04:40:56.412+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-26T04:40:56.490+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/flatten.py", line 153, in transform_and_load_forex_data
    cursor.executemany(insert_query, data_to_insert)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1403, in executemany
    self.execute(command, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 989, in execute
    ret = self._execute_helper(query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 700, in _execute_helper
    ret = self._connection.cmd_query(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1351, in cmd_query
    ret = self.rest.request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 500, in request
    return self._post_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 748, in _post_request
    ret = self.fetch(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 863, in fetch
    ret = self._request_exec_wrapper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 913, in _request_exec_wrapper
    return_object = self._request_exec(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 1080, in _request_exec
    raw_ret = session.request(
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 330, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 145, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 106, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 104, in do_poll
    return poll_obj.poll(t)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-26T04:40:56.525+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=transform_forex_data_dag, task_id=transform_and_load_forex_data, run_id=manual__2024-12-26T04:39:01.726240+00:00, execution_date=20241226T043901, start_date=20241226T043904, end_date=20241226T044056
[2024-12-26T04:40:56.557+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T04:40:56.662+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=403, status='terminated', exitcode=2, started='04:39:04') (403) terminated with exit code 2
