[2024-12-19T05:38:57.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T05:38:57.829+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_news_and_insert_all_countries.fetch_and_insert_news_all_countries manual__2024-12-19T05:38:54.131524+00:00 [queued]>
[2024-12-19T05:38:57.844+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_news_and_insert_all_countries.fetch_and_insert_news_all_countries manual__2024-12-19T05:38:54.131524+00:00 [queued]>
[2024-12-19T05:38:57.845+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-19T05:38:57.871+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_insert_news_all_countries> on 2024-12-19 05:38:54.131524+00:00
[2024-12-19T05:38:57.881+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1003) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T05:38:57.883+0000] {standard_task_runner.py:72} INFO - Started process 1006 to run task
[2024-12-19T05:38:57.884+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_news_and_insert_all_countries', 'fetch_and_insert_news_all_countries', 'manual__2024-12-19T05:38:54.131524+00:00', '--job-id', '2586', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connector_dag.py', '--cfg-path', '/tmp/tmp9f8zsvfu']
[2024-12-19T05:38:57.888+0000] {standard_task_runner.py:105} INFO - Job 2586: Subtask fetch_and_insert_news_all_countries
[2024-12-19T05:38:57.968+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_news_and_insert_all_countries.fetch_and_insert_news_all_countries manual__2024-12-19T05:38:54.131524+00:00 [running]> on host 8348eb091483
[2024-12-19T05:38:58.109+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_news_and_insert_all_countries' AIRFLOW_CTX_TASK_ID='fetch_and_insert_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T05:38:54.131524+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T05:38:54.131524+00:00'
[2024-12-19T05:38:58.111+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T05:38:58.147+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-19T05:38:58.149+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-19T05:38:58.151+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-19T05:38:58.153+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-19T05:38:58.737+0000] {logging_mixin.py:190} INFO - Processing news for country: IN
[2024-12-19T05:38:58.739+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-01-01 to 2020-01-02 for IN...
[2024-12-19T05:39:00.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T05:39:00.391+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: fetch_news_and_insert_all_countries.fetch_and_insert_news_all_countries manual__2024-12-19T05:38:54.131524+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-12-19T05:39:00.393+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: fetch_news_and_insert_all_countries.fetch_and_insert_news_all_countries manual__2024-12-19T05:38:54.131524+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-12-19T05:39:00.397+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-12-19T05:39:33.317+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-19T05:39:33.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T05:39:33.324+0000] {process_utils.py:132} INFO - Sending 15 to group 1006. PIDs of all processes in the group: [1006]
[2024-12-19T05:39:33.325+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1006
[2024-12-19T05:39:33.326+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T05:39:33.327+0000] {connection.py:789} INFO - closed
[2024-12-19T05:39:33.546+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-19T05:39:33.595+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/snowflake_connector_dag.py", line 59, in fetch_and_insert_news_for_countries
    cursor.execute(insert_query, (
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 989, in execute
    ret = self._execute_helper(query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 700, in _execute_helper
    ret = self._connection.cmd_query(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1351, in cmd_query
    ret = self.rest.request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 500, in request
    return self._post_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 748, in _post_request
    ret = self.fetch(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 863, in fetch
    ret = self._request_exec_wrapper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 913, in _request_exec_wrapper
    return_object = self._request_exec(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 1080, in _request_exec
    raw_ret = session.request(
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 330, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 145, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 106, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 104, in do_poll
    return poll_obj.poll(t)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-19T05:39:33.623+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_news_and_insert_all_countries, task_id=fetch_and_insert_news_all_countries, run_id=manual__2024-12-19T05:38:54.131524+00:00, execution_date=20241219T053854, start_date=20241219T053857, end_date=20241219T053933
[2024-12-19T05:39:33.649+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T05:39:33.700+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1006, status='terminated', exitcode=2, started='05:38:56') (1006) terminated with exit code 2
